// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SahilNameSorterCore.DataAccess;

namespace SahilNameSorterCore.DataAccess.Migrations
{
    [DbContext(typeof(NameSorterContext))]
    [Migration("20181012042153_NewColumnNameValidation")]
    partial class NewColumnNameValidation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SahilNameSorterCore.Entities.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName");

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender");

                    b.Property<string>("Namevalidation");

                    b.Property<string>("Surname");

                    b.HasKey("ID", "FullName");

                    b.ToTable("Person");

                    b.HasData(
                        new { ID = 1, FullName = "Sahil Deshpande", FirstName = "Sahil", Surname = "Deshpande" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
